name: C/C++ CI

on:
  push:
    branches: [ submission ]
  pull_request:
    branches: [ submission ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: Install CMake 3.17.3
      uses: lukka/get-cmake@v3.17.3
    - name: Run CMake
      uses: lukka/run-cmake@v2.5
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtBasic
